In [17]:
def tambah (a,b):
    print(a+b) 

def kurang(a,b):
    print(a-b)

def kali (a,b):
    print(a*b)

def bagi (a,b):
    print(a//b)

def pangkat (a,b):
    print(a**b)

try:
    a = int(input(" Masukan Angka 1 = "))
    c = input("Masukan Operator angkanya ")
    b = int(input("Masukan  Angka 2 = "))

    if c == "+":
        print(tambah(a,b))
    elif c =="-":
        kurang(a,b)
        print(kurang(a,b))
    elif c =="x":
        print(kali(a,b))
    elif c ==":":
        print(bagi(a,b))
    else:
        print("Operator tidak ditemukan")

except ValueError:
    print("Tipe data salah")


 Masukan Angka 1 = 10
Masukan Operator angkanya +
Masukan  Angka 2 = 10
20
None


In [18]:
import numpy as np

In [19]:
c = np.array([1,2,3])

In [20]:
c

array([1, 2, 3])

## One Dimensional Array

### Indexing dan Slicing

In [21]:
c[0]

1

In [32]:
array_1 = [1,2,3,4,5,6,7,8]

In [33]:
array_1[3:]

[4, 5, 6, 7, 8]

In [44]:
c = np.array(array_1)
c.shape()

TypeError: 'tuple' object is not callable

## Two Dimensional Array, Consist of list of list

In [24]:
list_of_list = [[1,2,3],[4,5,6],[7,8,9]]

In [25]:
list_of_list[0]

[1, 2, 3]

In [27]:
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
array_2 = np.array(list_of_list)
array_2
print(array_2.shape)

(3, 3)


In [37]:
list_of_list = [[1,2],[3,4],[5,6]]
array_3 = np.array(list_of_list)
print(array_3.shape)
array_3

(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
#np.zeros
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
print(np.zeros(8))
print(np.zeros([3,2])) #3 baris 2 kolom

[0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [46]:
#np.ones
print(np.ones(4))
print(np.ones([4,2]))

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [49]:
#np.empty ##generate random values
np.empty(5)
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [55]:
#np.arange
# untuk array tapi gabisa buat lebih dari 1 dimensi
np.arange(10)
print(np.arange(1,10,1))

[1 2 3 4 5 6 7 8 9]


In [56]:
np.arange(0,30,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [60]:
x = np.array([1,2,3,4,5,6,7,8,9,0,70])

#append
print(np.append(x,[10,11]))

#delete
print(np.delete(x,2))

#sort
print(np.sort(c))

[ 1  2  3  4  5  6  7  8  9  0 70 10 11]
[ 1  2  4  5  6  7  8  9  0 70]
[1 2 3 4 5 6 7 8]


In [64]:
#ndim
print(c.ndim)
print(c.size)

1
8


In [69]:
d = np.zeros([2,2])

print(d.ndim)

#size
print(d.size)

2
4


In [70]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#reshape
print(x.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [81]:
y = np.array([1,2,3,4,5,6,7,8,9,10])

print(y.size)
#reshape
print(y[:-1].reshape(3,3))

10
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
array_3 = np.array([[1,2,3,4]])
array_3.shape
array_3

array([[1, 2, 3, 4]])

In [80]:
#np.newaxis
array_4 = np.array([4,5,6])
array_4[np.newaxis,:]
array_4[np.newaxis].shape

(1, 3)

In [83]:
array_5 = np.array([[1,2,3,4]])
array_6 = np.array([[5,6,7,8]])

#menumpuk array yang udah dibuat jadi array baru
np.vstack([array_5,array_6])
print(np.vstack([array_5,array_6]).shape)

(2, 4)


### habis break

In [85]:
#np.expand_dims
array_7 = np.array([3,4,5,6,7,8,9])
array_8 = np.expand_dims(array_7,axis=1)
array_9 = np.expand_dims(array_7,axis=0)
print(array_8)
print(array_8.shape)
print(array_9)
print(array_9.shape)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(7, 1)
[[3 4 5 6 7 8 9]]
(1, 7)


In [86]:
array_7 = np.array([3,4,5,6,7,8,9])
print(array_7[array_7>5])
print(array_7[array_7==8])
print(array_7[array_7<=4])

[6 7 8 9]
[8]
[3 4]


In [87]:
array_11 =np.array([[3,5,7],[8,9,10],[-1,-2,-3]])
array_11.shape
print(array_11[array_11>5])

[ 7  8  9 10]


## KUIS :(

In [3]:
jam_pasir = int(input("How Tall?"))

x = 1
y = jam_pasir

while x <= jam_pasir:
    print((x*'')+y*'*')
    y = y-1
    x = x+1

x = 1
y = jam_pasir

while x <= jam_pasir:
    print((y*'')+x*'*')
    y = y-1
    x = x+1

How Tall?11
***********
**********
*********
********
*******
******
*****
****
***
**
*
*
**
***
****
*****
******
*******
********
*********
**********
***********


In [4]:
# dijadiin tugas
jam_pasir = int(input("How Tall?"))

x = 1
y = jam_pasir

while x <= jam_pasir:
    print((x*' ')+y*'*')
    y = y-2
    x = x+1

x = 1
y = jam_pasir

while x <= jam_pasir:
    print((y*' ')+x*'*')
    y = y-1
    x = x+2

How Tall?11
 ***********
  *********
   *******
    *****
     ***
      *
       
        
         
          
           
           *
          ***
         *****
        *******
       *********
      ***********


In [ ]:
#stack
array_14 = np.array([])

In [112]:
#vsplit
array_19 = np.array([[1,2,3,4,5,6],[4,5,6,7,5,6]])
print(array_19)
print('Horizontal Split')
print(np.hsplit(array_19,2))
print('Vertical Split')
print(np.vsplit(array_19,2))


[[1 2 3 4 5 6]
 [4 5 6 7 5 6]]
Horizontal Split
[array([[1, 2, 3],
       [4, 5, 6]]), array([[4, 5, 6],
       [7, 5, 6]])]
Vertical Split
[array([[1, 2, 3, 4, 5, 6]]), array([[4, 5, 6, 7, 5, 6]])]


## Operasi Aritmetik Antar 2 Array

In [113]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
print(array_a + array_b)

[4 6 8]


In [115]:
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_c-array_d)

[[-5 -5 -5]
 [-5 -5 -5]]


In [117]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[1,2,3],[4,5,6]])
array_d = np.array([[6,7,8],[9,10,11]])
print(array_a.sum())
print(array_c.sum())
print(array_c.sum(axis=0)) #axis 0 kebawah(baris)
print(array_c.sum(axis=1))

6
21
[5 7 9]
[ 6 15]


In [120]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
array_c = np.array([[5,2,3],[4,5,6]])
print(array_a.max())
print(array_c.max())
print(array_c.max(axis=0))
print(array_c.min(axis=0))

3
6
[5 5 6]
[4 2 3]


## Transposing

In [121]:
array_c = np.array([[1,2,3],[4,5,6]])
print(array_c)
print(array_c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [122]:
print(array_c.T)

[[1 4]
 [2 5]
 [3 6]]


In [125]:
array_d = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
print(array_d.T)
print(array_d.T.shape)


[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]
 [ 5  8 11]]
(5, 3)


In [126]:
np.random.random([3,2])*100

array([[96.22748996, 20.71881464],
       [48.41770865, 72.10209434],
       [ 9.13599975, 86.66841501]])

In [127]:
array_random = np.random.random([3,2])*100
print(array_random)
print(array_random.flatten())

[[ 2.24193663 35.10783628]
 [17.85262708 93.44281806]
 [ 6.13752466  1.37052913]]
[ 2.24193663 35.10783628 17.85262708 93.44281806  6.13752466  1.37052913]


## Math Formulas Numpy

In [128]:
array_random = np.random.random([3,2])*100
print(array_random)
np.sum(array_random)

[[96.77928691 74.81443427]
 [86.96271079 74.98009363]
 [44.54861388 64.79412056]]


442.87926004663973

In [129]:
np.square(9)

81

In [130]:
np.sqrt(9)

3.0

In [132]:
x = np.log(1000000)
print(x)

13.815510557964274


In [133]:
np.exp(x)

999999.9999999995

HMMM KUIS

In [149]:
lowest = int(input("Please, Enter the Lowest Range Value:"))
upper = int(input("Please, Enter the upper Range Value:"))
print("Prime number in the range are ",lowest,"up to",upper,":")
for num in range(lowest,upper + 1):
     if num > 1:
        for i in range(2, num):
            if (num % i) == 0:
                break
        else:
            print(num)

Please, Enter the Lowest Range Value:10
Please, Enter the upper Range Value:30
Prime number in the range are  10 up to 30 :
11
13
17
19
23
29


## Tugas 2 Kelompok 1

In [1]:
inputTinggiSegitiga = int(input('how tall ? '))
t = 0

if inputTinggiSegitiga%2==0:
    t=inputTinggiSegitiga-1
else:
    t=inputTinggiSegitiga

for i in range(0,t):
    if (t-2*i)>0:
        print(' '*i+'*'*(t-2*i))
    else:
        k=t-i-1
        print(' '*k+'*'*(t-2*k))

how tall ? 11
***********
 *********
  *******
   *****
    ***
     *
    ***
   *****
  *******
 *********
***********
